version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: research_app
      POSTGRES_USER: statscribe
      POSTGRES_PASSWORD: ss123
    volumes:
      - ./db/data:/var/lib/postgresql/data
    ports:
      - "5434:5434"
